kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ebs-static
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  # PV name
  volumeName: ebs-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: ebs-static
#   namespace: expense
#   labels:
#     purpose: "ebs-static-test"
# spec:
#   nodeSelector:
#     topology.kubernetes.io/zone: us-east-1a
#   containers:
#   - name: nginx
#     image: nginx
#     volumeMounts:
#     - name: persistent-storage
#       mountPath: /usr/share/nginx/html
#   volumes:
#   - name: persistent-storage
#     persistentVolumeClaim:
#       claimName: ebs-static
kind: pod
apiVersion: apps/v1v1
metadata:
  name: nginx
  namespace: expense
  labels:
    purpose: "ebs-static-test"
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1a
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html/
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-static 
# ---
# kind: Service
# apiVersion: v1
# metadata:
#   name: nginx
# spec:
#   type: Loadbalancer
#   selector: # labels are used as selectors
#     purpose: "ebs-static-volume"
#   ports:
#   - protocol: TCP
#     port: 80 # service port
#     targetPort: 80
#     nodePort: 30007
---    
kind: Service
apiVersion: v1
metadata:
  name: nginx-lb
  namespace: expense
spec:
  type: LoadBalancer
  selector: # labels are used as selectors
    purpose: "ebs-static-test"
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80
    nodePort: 30007


