apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic-prakash
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "efs-expense-prakash"
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-dynamic-prakash
  labels:
    purpose: "efs-dynamic-demo-prakash"
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-dynamic
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-lb-prakash
spec:
  type: LoadBalancer
  selector: # labels are used as selectors
    purpose: "efs-dynamic-demo-prakash"
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80
    nodePort: 30008