apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica
  namespace: expense
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
