apiVersion: v1
kind: Pod
metadata:
  name: nginx-nodeselector
  namespace: expense
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1c
  tolerations:
    - key: "key"
      operator: "Equal"
      value: "value1"
      effect: "Noexecute"