apiVersion: apps/v1
kind: Deployment
metadata:
  name: ninx-deployment
  namespace: expense
  labels:
    project: expense
    app: expense-app
    version: "1.0"
spec:
  replicas: 3
  selector:
    matchLabels:
      project: expense
      app: expense-app
      version: "1.0"
  templete:
    metadata:
      labels:
        project: expense
        app: expense-app
        version: "1.0"
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: Deployment-service
  namespace: expense
spec:
  type: NodePort
  selector:
      project: expense
      app: expense-app
      version: "1.0"
  ports:
  - protocol: TCP 
    port: 80
    targetport: 80
    NodePort: 30007

    
        