apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: expense
  labels:
    project: expense
    app: expense-app
    version: "1.0"
spec:
  replicas: 3
  selector:
    matchLabels:
      project: expense
      app: expense-app
      version: "1.0"
  template:
    metadata:
      labels:
        project: expense
        app: expense-app
        version: "1.0"
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: deployment-service
  namespace: expense
spec:
  type: LoadBalancer
  selector:
    project: expense
    app: expense-app
    version: "1.0"
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    NodePort: 30007
